parallelism: 4
executor:
  name: win/default
steps:
  - checkout
  - run:
      command: ./scripts/assert-changed-files.sh "packages/*|.circleci/*"
      shell: bash.exe
  - attach_workspace:
      at: ./
  - run: npm i -g node-gyp
  - run: npm rebuild
  - run:
      name: Run tests
      command: yarn jest --ci --runInBand ((yarn jest --listTests) | Foreach-Object {$_ -replace '.*\\packages', 'packages'} | Foreach-Object {$_ -replace '\\', '/'} | circleci tests split --split-by=timings)
      environment:
        NODE_OPTIONS: --max-old-space-size=2048
        GENERATE_JEST_REPORT: true
        JEST_JUNIT_OUTPUT_DIR: ./test-results/jest-node/
        JEST_JUNIT_OUTPUT_NAME: results.xml
  - store_test_results:
      path: ./test-results/jest-node/
